# Generated by Django 4.1.4 on 2022-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='vessels',
            field=models.ManyToManyField(blank=True, to='main_app.vessel'),
        ),
    ]
