# Generated by Django 3.1.4 on 2020-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(verbose_name='watering date'),
        ),
    ]
