# Generated by Django 3.1.4 on 2020-12-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201214_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watering',
            old_name='watering',
            new_name='type',
        ),
    ]
