# Generated by Django 3.1.4 on 2020-12-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='vessels',
            field=models.ManyToManyField(to='main_app.Vessel'),
        ),
    ]
