# Generated by Django 3.2.6 on 2021-08-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_plant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user',
            new_name='owner',
        ),
    ]
